#!/usr/bin/env bash
#creating a loop using if elif and else setting var equal to mutliples of..
for x in {1..100}
do
    if [[ $((x % 5)) -eq 0 ]] && [[ $((x % 3)) -eq 0 ]]
    then
	echo "FizzBuzz"
    elif [ $((x % 3)) -eq 0 ]
	 then
	 echo "Fizz"
    elif [ $((x % 5)) -eq 0 ]
	 then
	     echo "Buzz"
    else
	echo "$x"
    fi
done

