#!/usr/bin/env bash
#creating a script that uses nested if statment in a loop
file=school
if [ -a $file]
then
    echo " $file file esists "

    if [ -b $file ]
    then
	echo " $file file is not empty "
    else
	echo " $file file is empty"
    if

    if [ -c $file ]
    then
	echo "$file is a regular file"
    if
    else
    echo "$file file does not exist"

fi